### ISSUE TITLE
Contribution guidelines and dependencies

### ISSUE THREAD

**Issue by Nelson-Gon** [davidsjoberg/similiars#2]
Hello,

I came across the package via Twitter. I would like to propose addition of a `contributing.md` file to describe how contributions should be made.  For instance, who gets to be listed as a `ctb` in the description file?

Regarding the description, since the package depends on `stringr`, would this be rather listed in the `Depends` field? I ask because the example on Twitter, seemed to require an explicit call to `stringr`.

Thank you,

Nelson

**Comment by davidsjoberg** [comment]
Thank you for you pull request! I merged it into master. 

As for contributing.md, what is the convention? 

about stringr, it is to get the vector `fruit` to make simple examples in readme and in documentation. Can  I move stringr to depends and it will still work in documentation examples?

**Comment by Nelson-Gon** [comment]
Hi thank you for the response. On taking a second look, it seems `stringr` is not heavily depended on so leaving it in `Imports` suffices. Putting it in Depends would load `stringr` on library calls, which seems unnecessary. 

About the `contributing.md`, I am not sure what the convention is. However, perhaps a simple guide would do? Maybe take some inspiration from `tidyverse`(or some other repo)? 

Something unrelated to this issue, is the name `similiar` intended in place of `similar`?! Is it in fact sort of a pun to show that similiar in this case would be close to similar?

**Comment by davidsjoberg** [comment]
Yes, it was a pun. But I might change it. at least in the function names :)
